# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        MainWindow.setMinimumSize(QtCore.QSize(400, 250))
        MainWindow.setMaximumSize(QtCore.QSize(400, 250))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.new_hd_check = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.new_hd_check.setFont(font)
        self.new_hd_check.setObjectName("new_hd_check")
        self.horizontalLayout.addWidget(self.new_hd_check)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.location_label.setFont(font)
        self.location_label.setObjectName("location_label")
        self.horizontalLayout.addWidget(self.location_label)
        self.location_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.location_line_edit.setObjectName("location_line_edit")
        self.horizontalLayout.addWidget(self.location_line_edit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.to_layout = QtWidgets.QHBoxLayout()
        self.to_layout.setObjectName("to_layout")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_label.sizePolicy().hasHeightForWidth())
        self.to_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.to_label.setFont(font)
        self.to_label.setAlignment(QtCore.Qt.AlignCenter)
        self.to_label.setObjectName("to_label")
        self.to_layout.addWidget(self.to_label)
        self.to_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_line_edit.sizePolicy().hasHeightForWidth())
        self.to_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.to_line_edit.setFont(font)
        self.to_line_edit.setObjectName("to_line_edit")
        self.to_layout.addWidget(self.to_line_edit)
        self.gridLayout.addLayout(self.to_layout, 5, 0, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 6, 0, 1, 1)
        self.from_layout = QtWidgets.QHBoxLayout()
        self.from_layout.setObjectName("from_layout")
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_label.sizePolicy().hasHeightForWidth())
        self.from_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.from_label.setFont(font)
        self.from_label.setAlignment(QtCore.Qt.AlignCenter)
        self.from_label.setObjectName("from_label")
        self.from_layout.addWidget(self.from_label)
        self.from_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_line_edit.sizePolicy().hasHeightForWidth())
        self.from_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.from_line_edit.setFont(font)
        self.from_line_edit.setInputMask("")
        self.from_line_edit.setObjectName("from_line_edit")
        self.from_layout.addWidget(self.from_line_edit)
        self.gridLayout.addLayout(self.from_layout, 4, 0, 1, 1)
        self.session_layout = QtWidgets.QHBoxLayout()
        self.session_layout.setObjectName("session_layout")
        self.choose_session_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_session_label.sizePolicy().hasHeightForWidth())
        self.choose_session_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choose_session_label.setFont(font)
        self.choose_session_label.setToolTipDuration(-1)
        self.choose_session_label.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_session_label.setObjectName("choose_session_label")
        self.session_layout.addWidget(self.choose_session_label)
        self.choose_session_combo = QtWidgets.QComboBox(self.centralwidget)
        self.choose_session_combo.setObjectName("choose_session_combo")
        self.session_layout.addWidget(self.choose_session_combo)
        self.refresh_session_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_session_button.setObjectName("refresh_session_button")
        self.session_layout.addWidget(self.refresh_session_button)
        self.gridLayout.addLayout(self.session_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        self.menuVersion = QtWidgets.QMenu(self.menubar)
        self.menuVersion.setObjectName("menuVersion")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuVersion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HD-HD Move"))
        self.new_hd_check.setText(_translate("MainWindow", "New HD"))
        self.location_label.setText(_translate("MainWindow", "Location:"))
        self.to_label.setText(_translate("MainWindow", "To HD:"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.from_label.setText(_translate("MainWindow", "From HD:"))
        self.choose_session_label.setText(_translate("MainWindow", "Choose session:"))
        self.refresh_session_button.setText(_translate("MainWindow", "Refresh list"))
        self.menuVersion.setTitle(_translate("MainWindow", "Version"))

